// // Airthmatic operator 
let num1 = 23;
let num2 = 7;
console.log(num1 + num2)
console.log(num1 - num2)
console.log(num1 * num2)
console.log(num1 / num2)
console.log(num1 % num2)
console.log(num1**2)
// // comparision operator
let a = 23;
let b = 45;
let c = 23
console.log(a == b) //checking equlity 
console.log(a != b) //checking Not Equal  
console.log(a > b) //checking Gerater
console.log(a < b) //checking lesser 
console.log(a <= b) //checking greater or equal  
console.log(a >= b) //checking lessear or equal 
console.log(a === c) // strict comparision 
// Logical AND operator
let a = true;
let b = false; 
let c = true;
console.log(a && b);
console.log(b && a);
console.log(a && c);
console.log(c && a);
console.log(b && c);
console.log(c && b);
// logical OR operator
let a = true;
let b = false;
let c = false;
console.log(a || b) 
console.log(b || c) 
console.log(c || a)
// logical NOT operator
let a = 23;
let b = NaN;
let sum = 45;
console.log(!a)
console.log(!b)
console.log(!sum)
// Bitwise operator

// bitwise And
let a = 6
let b = 5
console.log(a & b)

// bitwise or
let a = 5
let b= 3
console.log(5 | 3)

// bitwise XOR
console.log( a ^ b )

// bitwise NOT 
console.log(~a)

// left shift 
console.log( a << 2)

// Right shift
console.log(a >> 2)

// ternary operator
let myAge = 12;
(myAge <= 18 ) ? (console.log("can vote")) : (console.log("can not vote"))



